// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/10/2025, 9:51:41 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["C:/Users/Stephany Andrino/Desktop/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stephany Andrino/Desktop/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stephany Andrino/Desktop/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stephany Andrino/Desktop/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stephany Andrino/Desktop/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Stephany Andrino/Desktop/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Stephany Andrino/Desktop/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Stephany Andrino/Desktop/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stephany Andrino/Desktop/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stephany Andrino/Desktop/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stephany Andrino/Desktop/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;